export GOPATH=~/codes/go/opencourse
go fmt labix.org/v2/mgo
go fmt labix.org/v2/mgo/bson
go fmt github.com/djimenez/iconv-go
go fmt spider
go fmt logx
go fmt util/htmlutil
go fmt util/stringutil
go fmt util/dateutil
go fmt constant
go fmt preprocess
go build labix.org/v2/mgo
go build labix.org/v2/mgo/bson
go build github.com/djimenez/iconv-go
go build spider
go build logx
go build util/htmlutil
go build util/stringutil
go build util/dateutil
go build constant
go build preprocess
go install labix.org/v2/mgo
go install labix.org/v2/mgo/bson
go install github.com/djimenez/iconv-go
go install logx
go install spider
go install util/htmlutil
go install util/stringutil
go install util/dateutil
go install constant
go install preprocess
go build main.go
